# Generated by Django 5.1.7 on 2025-03-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_rate', models.FloatField()),
                ('cbm_rate', models.FloatField()),
            ],
        ),
    ]
