# Generated by Django 5.1.7 on 2025-05-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting_app', '0003_rates_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additionalcosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Taxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Enter the tax rate as a percentage, e.g., 16.00 for 16%', max_digits=5, verbose_name='Tax percentage')),
            ],
        ),
    ]
