# Generated by Django 5.1.7 on 2025-05-13 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting_app', '0004_additionalcosts_taxes'),
        ('shipments', '0010_remove_invoice_paid_invoice_due_date_invoice_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalcosts',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipments.shipment'),
        ),
    ]
