# Generated by Django 5.1.7 on 2025-05-15 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting_app', '0005_additionalcosts_shipment'),
        ('users', '0008_alter_business_business_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxes',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.business'),
        ),
    ]
