# Generated by Django 5.1.7 on 2025-05-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting_app', '0006_taxes_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='rates',
            name='route',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
