# Generated by Django 5.1.7 on 2025-05-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting_app', '0007_rates_route'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rates',
            options={'verbose_name_plural': 'Shipping Rates'},
        ),
        migrations.AddField(
            model_name='rates',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rates',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rates',
            name='cbm_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rates',
            name='weight_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
