# Generated by Django 5.1.7 on 2025-05-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting_app', '0008_alter_rates_options_rates_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalcosts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='additionalcosts',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='taxes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='taxes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
