# Generated by Django 5.1.7 on 2025-04-16 19:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_roles_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff')], default='staff', max_length=10),
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('currency_id', models.PositiveIntegerField()),
                ('business_logo', models.ImageField(blank=True, help_text='Upload your business logo', null=True, upload_to='business_logos/')),
                ('website', models.URLField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('alternate_number', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('landmark', models.CharField(max_length=100)),
                ('time_zone', models.CharField(max_length=100)),
                ('tax_label_1', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_number_1', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_label_2', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_number_2', models.CharField(blank=True, max_length=50, null=True)),
                ('fy_start_month', models.PositiveSmallIntegerField(help_text='Month number (1 for January, etc.)')),
                ('accounting_method', models.CharField(choices=[('fifo', 'FIFO (First In First Out)'), ('lifo', 'LIFO (Last In First Out)')], default='fifo', max_length=4)),
                ('owner_email', models.EmailField(blank=True, editable=False, max_length=254, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
