# Generated by Django 5.1.7 on 2025-04-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_role_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_logo',
            field=models.ImageField(blank=True, help_text='Upload your business logo', null=True, upload_to='static/images/business_logos/'),
        ),
    ]
