# Generated by Django 5.1.7 on 2025-05-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_business_alter_business_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_logo',
            field=models.ImageField(blank=True, help_text='Upload your business logo', null=True, upload_to='images/business_logos/'),
        ),
    ]
