# Generated by Django 5.1.7 on 2025-04-28 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('users', '0007_customuser_business_alter_business_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.business'),
        ),
        migrations.AddField(
            model_name='payment',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.business'),
        ),
    ]
