# Generated by Django 5.1.7 on 2025-03-28 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='clients.client'),
        ),
        migrations.DeleteModel(
            name='ShipmentStatusHistory',
        ),
    ]
