# Generated by Django 5.1.7 on 2025-03-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_alter_shipment_client_delete_shipmentstatushistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(max_length=200),
        ),
    ]
