# Generated by Django 5.1.7 on 2025-03-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='estimated_delivery',
            new_name='estimated_delivery_date',
        ),
        migrations.AddField(
            model_name='shipment',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipment_cost',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
