# Generated by Django 5.1.7 on 2025-04-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0007_invoice_business_shipment_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='recepient_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='recepient_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipment_complete',
            field=models.BooleanField(default=False),
        ),
    ]
