# Generated by Django 5.1.7 on 2025-05-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0008_shipment_recepient_name_shipment_recepient_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='quantity',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
