# Generated by Django 5.1.7 on 2025-05-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0011_alter_shipment_shipment_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
